### ISSUE TITLE
BCrypt version 4.0.2 and System.Runtime.CompilerServices.Runtime 4.7.1 compatibility issue

### ISSUE THREAD

**Issue by jijoe** [BcryptNet/bcrypt.net#91]
My team is using BCrypt version 4.0.2 and we've to use v4.7.1 of System.Runtime.CompilerServices.Unsafe due to another (transitive) dependency. 

At runtime, we see the following error when invoking the `BCrypt.Net.BCrypt.HashPassword(String inputKey, String salt, Boolean enhancedEntropy, HashType hashType)` method.

```
[16:54:50]F:			 [MM.Core.NUnitTests.UnitTests.BusinessLayerTests.HelperTests.PasswordHashingHelperTests.GenerateHash_given_password_and_salt_returns_hashed_value] System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[16:54:50]F:			 [MM.Core.NUnitTests.UnitTests.BusinessLayerTests.HelperTests.PasswordHashingHelperTests.GenerateHash_given_password_and_salt_returns_hashed_value]    at System.ReadOnlySpan`1..ctor(T[] array)
   at System.ReadOnlySpan`1.op_Implicit(T[] array)
   at BCrypt.Net.BCrypt.HashPassword(String inputKey, String salt, Boolean enhancedEntropy, HashType hashType) in I:\bcrypt.net\src\BCrypt.Net\BCrypt.cs:line 669
   at MM.Core.BusinessLayer.Helpers.PasswordHashingHelper.GenerateHash(String password, String salt) in C:\BuildAgent\work\50ad46f03ff53e94\Core\BusinessLayer\Helpers\PasswordHashingHelper.cs:line 23
   at MM.Core.NUnitTests.UnitTests.BusinessLayerTests.HelperTests.PasswordHashingHelperTests.GenerateHash_given_password_and_salt_returns_hashed_value() in C:\BuildAgent\work\50ad46f03ff53e94\Core\NUnitTests\UnitTests\BusinessLayerTests\HelperTests\PasswordHashingHelperTests.cs:line 69
```

(Assembly) version 4.0.4.1 is part of System.Runtime.CompilerServices.Unsafe v4.5.3, I believe.

According to [Nuget v4.0.2 documentation](https://www.nuget.org/packages/BCrypt.Net-Next/4.0.2), it depends on System.Memory >= v4.5.4 which in turn depends on System.Runtime.CompilerServices.Unsafe >= 4.5.4. This means it **should** work with v4.7.1, but doesn't seem to.

Has version 4.0.2 BCrypt been tested with version 4.7.1 of System.Runtime.CompilerServices.Unsafe?

**Comment by ChrisMcKee** [comment]
We use it internally in a fwk 4.6 sln, 4.7.2 and net core 2.1 and 3.1.

I'll update and re run the integration tests.

**Comment by ChrisMcKee** [comment]
K if I use .net 4.7.1 (you should at least move to 4.7.2 https://github.com/microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md ) the following assembly redirect is added 

https://github.com/BcryptNet/bcrypt.net/tree/main/IntegrationTest/TestVariousVersionsOfDotNet/DotNet4

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Beyond that it worked fine.

**Comment by jijoe** [comment]
I really appreciate the quick turnaround on this, Chris. We'll test this on our end to confirm settings + even look at moving to version 5.0.0 of System.Runtime.CompilerServices.Unsafe

**Comment by jijoe** [comment]
So it turns out this problem we caused by use of Nunit 3 runner for our unit tests step in TeamCity builds. Switching to vstest for unit test step fixed this problem for us.

**Comment by ChrisMcKee** [comment]
I switched to xunit when nunit stagnated (post .net core launch after DNX); .net assembly binding is my endless hell 😆
